markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: pygments
#pygments: true
safe: true
#auto: false 
paginate: 8 
paginate_path: "page:num"
gems: [jekyll-paginate]

# presonal config
domain: 
title: Robin's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: Robin 
email: lyp40293@gmail.com
github: lypRobin

config:
  js_dir:
  img_dir:
  css_dir:
